Update labadmin-script_server

diff --git a/labadmin-script_server b/labadmin-script_server
--- a/labadmin-script_server
+++ b/labadmin-script_server
@@ -2,9 +2,10 @@
 #===================================================================================
 # LABADMIN SCRIPT SERVER
 #         FILE: labadmin-script_server
-#        USAGE: labadmin-script_server -h hostname -o os -a list|get|exec_ok|exec_error [-s script] [-m exec_message]
+#        USAGE: labadmin-script_server -h hostname -r repository_name -a list|get|exec_ok|exec_error [-s script] [-m exec_message]
 #
 #  DESCRIPTION: Labadmin script server manager
+#               Manage actions to do: list pending scripts, show script code, save exec status (exec_ok or exec_error)
 #
 #       AUTHOR: Leonardo Marco (labadmin@leonardomarco.com)
 #	   LICENSE: GNU General Public License v3.0
@@ -12,21 +13,23 @@
 #      CREATED: 28.06.2022
 #=================================================================================== 
 
-
 #===============================================================================
 #  GLOBAL VARIABLES
 #===============================================================================
-readonly scripts_path=$(dirname "$(readlink -f "$0")")
+# Base path of scripts repositories dirs: linux, w7, w10, etc.
+readonly repositories_path=$(dirname "$(readlink -f "$0")")		
+
+
 
 
 #=== FUNCTION ==================================================================
 #        NAME: help
 # DESCRIPTION: Show help and exit 
-# PARAMETERS:
+#  PARAMETERS:
 #	$1	Exit code value
 #===============================================================================
 function help() {
-	echo "Usage: $(basename "$0") -h hostname -o os -a list|get|exec_ok|exec_error [-s script] [-m exec_message]"
+	echo "Usage: $(basename "$0") -h hostname -r repository_name -a list|get|exec_ok|exec_error [-s script] [-m exec_message]"
 	exit "$1"
 }
 
@@ -34,19 +37,19 @@ function help() {
 #=== FUNCTION ==================================================================
 #        NAME: check_params
 # DESCRIPTION: Checks input parameters and load values
-# PARAMETERS:
+#  PARAMETERS:
 #	$@	All parameter from command line
 #===============================================================================
 function check_params() {
-	while getopts ":h:o:a:s:m:" option
+	while getopts ":h:r:a:s:m:" option
 	do		
 		case $option in
 		h)			
 			readonly hostname="$OPTARG"
 		;;
-		o)
-			readonly stype="$OPTARG"
-			readonly scripts_dir="${scripts_path}/${stype}/"
+		r)
+			readonly repository="$OPTARG"
+			readonly repository_path="${repositories_path}/${repository}/"
 		;;
 		a)
 			readonly action="$OPTARG"
@@ -58,19 +61,19 @@ function check_params() {
 			readonly exec_msg="$OPTARG"
 		;;
 		?)
-			echo "$0: incorrect option  $OPTARG"
+			echo "Incorrect option: $OPTARG"
 			exit 2
 		;;
 	   esac
 	done
 
-	[ "$script" ] && readonly script_path="${scripts_dir}/${script}/"
+	[ "$script" ] && readonly script_path="${repository_path}/${script}/"
 
 	if [ ! "$hostname" ]; then
 		echo "Hostname not present"
 		help 2
-	elif [ ! "$stype" ]; then
-	    echo "Script type not present"
+	elif [ ! "$repository" ]; then
+	    echo "Repository not present"
 		help 2 
 	elif [ ! "$action" ]; then
 	    echo "Action not present"
@@ -81,11 +84,11 @@ function check_params() {
 	elif [[ "$action" = @(get|exec_ok|exec_error) ]] && [ ! "$script" ]; then
 		echo "Script not present"
 		help 2  
-	elif [ ! -d "$scripts_path" ] || [ ! -r "$scripts_path" ]; then
-		echo "Cant access scripts directory: $scripts_path"
+	elif [ ! -d "$repositories_path" ] || [ ! -r "$repositories_path" ]; then
+		echo "Cant access repositories path: $repositories_path"
 		exit 2
-	elif [ ! -d "$scripts_dir" ] || [ ! -r "$scripts_dir" ]; then
-		echo "Cant access script type directory: $scripts_dir"
+	elif [ ! -d "$repository_path" ] || [ ! -r "$repository_path" ]; then
+		echo "Cant access repository path: $repository_path"
 		exit 2
 	fi
 }
@@ -93,22 +96,27 @@ function check_params() {
 
 #=== FUNCTION ==================================================================
 #        NAME: log
-# DESCRIPTION: write in log file using format: [date time] HOSTNAME ACTION EXEC_MSG
-
+# DESCRIPTION: write in log file using format: 
+#              [DATE TIME] [HOSTNAME] [ACTION] [SCRIPT] EXEC_MSG
+#  PARAMETERS:
+#		$1: hostname
+#		$2: action
+#		$3: script
+#		$4: exec_msg
 #===============================================================================
 function log() {
-    local hn="$hostname"
-	local a="$action"
-    local s="$script"
-    local em="$exec_msg"
+    local hn="$1"
+	local a="$2"
+    local s="$3"
+    local em="$4"
 
 	hn_width=8
-	hn="[${hn^^}]$(seq -s" " 1 $(($hn_width-${#hn}))|tr -d "[0-9]")"
+	hn="[${hn^^}]$(seq -s" " 1 $(($hn_width-${#hn}))|tr -d "[0-9]") "
     a_width=11
-    a="[${a^^}]$(seq -s" " 1 $(($a_width-${#a}))|tr -d "[0-9]")"
+    a="[${a^^}]$(seq -s" " 1 $(($a_width-${#a}))|tr -d "[0-9]") "
 	[ "$s" ] && s="[$s]"$'\t'
 
-	echo -e "[$(date "+%Y-%m-%d %H:%M:%S")] ${hn} ${a} ${em}" >> "${script_path}/log"
+	echo -e "[$(date "+%Y-%m-%d %H:%M:%S")] ${hn}${a}${s}${em}" >> "${script_path}/log"
 }
 
 
@@ -119,15 +127,15 @@ function log() {
 function action_list() {
 	IFS2="$IFS"; IFS=$'\n'
 
-	for s in $(ls "$scripts_dir"); do
+	for s in $(ls "$repository_path"); do
 		# Check if hostname match with script REGEX
 		re=$(echo "$s" | cut -f1 -d" ")	
 		[[ "$hostname" = $re ]] || continue
 
 		# Check if hostname is selected
-		bash "${scripts_dir}/${s}/select" "$hostname" || continue
+		bash "${repository_path}/${s}/select" "$hostname" || continue
 		
-		# List script!
+		# List script
 		echo "$s"
 	done
 	IFS="$IFS2"
@@ -140,9 +148,16 @@ function action_list() {
 #===============================================================================
 function action_get() {
 	# Show script
-	cat "${script_path}/script"	|| exit 1
-	log 
+	exec_msg=$(cat "${script_path}/script" 2>&1)
+	if [ $? -eq 0 ]; then
+		log "$hostname" "$action" "$script"
+		exit 0 
+	else
+		log "$hostname" "get_error" "$script" "${exec_msg//$'\n'/ \/ }"
+		exit 1
+	fi
 }
+
 
 
 #=== FUNCTION ==================================================================
@@ -150,7 +165,7 @@ function action_get() {
 # DESCRIPTION: Notify correct execution
 #===============================================================================
 function action_exec_ok() {
-	log 
+	log "$hostname" "$action" "$script" "${exec_msg}"
 }
 
 
@@ -159,7 +174,7 @@ function action_exec_ok() {
 # DESCRIPTION: Notify error execution
 #===============================================================================
 function action_exec_error() {
-	log 
+	log "$hostname" "$action" "$script" "$exec_msg" 
 }
 
 
