Update lss-srv

diff --git a/lss-srv b/lss-srv
--- a/lss-srv
+++ b/lss-srv
@@ -201,7 +201,7 @@ function get_hostname_inventory() {
 function action_list() {
 	# GET INVENTORY HOSTNAME (exit on error)
 	if [ "$check_hostnames" ]; then
-		get_hostname_inventory "$mac" || { log "$mac" "$hostname" "LIST_ERROR" "" "Error inventory get-hostname for mac: $m"; exit 1; }
+		get_hostname_inventory "$mac" || { log "$mac" "$hostname" "LIST_ERROR" "" "Error inventory get-hostname for mac: $mac"; exit 1; }
 	fi
 
 	# LIST PENDING SCRIPTS
@@ -250,13 +250,13 @@ function action_list() {
 # DESCRIPTION: Print script code, log action and exit
 #===============================================================================
 function action_get() {
-	local m=""
+	local em=""
 	
 	# PRINT HOSTNAME SCRIPT -> replace in script code LSS-HOSTNAME-REPLACE for MAC
 	if [ -e "${script_path}/hostname" ]; then
-		get_hostname_inventory "$mac" || { log "$m" "$hostname" "get_error" "$script_path" "Error inventory get-hostname for mac: $m"; exit 1; }
+		get_hostname_inventory "$mac" || { log "$mac" "$hostname" "get_error" "$script_path" "Error inventory get-hostname for mac: $mac"; exit 1; }
 		cat "${script_path}/script" | sed "s/LSS-HOSTNAME-REPLACE/${hostname_inventory}/g" 2>&1
-		m="${hostname} -> ${hostname_inventory}"
+		em="${hostname} -> ${hostname_inventory}"
 
 	# PRINT REGULAR SCRIPT
 	else
@@ -264,10 +264,10 @@ function action_get() {
 	fi
 
 	if [ $? -eq 0 ]; then
-		log "$mac" "$hostname" "$action" "$script_path" "$m"
+		log "$mac" "$hostname" "$action" "$script_path" "$em"
 		exit 0 
 	else
-		log "$mac" "$hostname" "get_error" "$script_path" "$m"
+		log "$mac" "$hostname" "get_error" "$script_path" "$em"
 		exit 1
 	fi
 }
