Update lss-srv

diff --git a/lss-srv b/lss-srv
--- a/lss-srv
+++ b/lss-srv
@@ -188,7 +188,7 @@ function get_hostname_inventory() {
 	# Update hostname_match
 	[ "$hostname" = "$hostname_inventory" ] && hostname_match="true"
 
-	return $?
+	return $r
 }
 
 
@@ -199,7 +199,7 @@ function get_hostname_inventory() {
 function action_list() {
 	# GET INVENTORY HOSTNAME (exit on error)
 	if [ "$check_hostnames" ]; then
-		get_hostname_inventory "$mac" || { log "$m" "$hostname" "get-hostname_error" "" "Error get-hostname for mac: $m"; exit 1; }
+		get_hostname_inventory "$mac" || { log "$m" "$hostname" "list_error" "" "Error inventory get-hostname for mac: $m"; exit 1; }
 	fi
 
 	# LIST PENDING SCRIPTS
@@ -236,7 +236,7 @@ function action_list() {
 function action_get() {
 	# SHOW HOSTNAME SCRIPT -> replace in script code LSS-HOSTNAME-REPLACE for MAC
 	if [ -e "${script_path}/hostname" ]; then
-		get_hostname_inventory "$mac" || { log "$m" "$hostname" "get-hostname_error" "$script_path" "Error get-hostname for mac: $m"; exit 1; }
+		get_hostname_inventory "$mac" || { log "$m" "$hostname" "get_error" "$script_path" "Error inventory get-hostname for mac: $m"; exit 1; }
 		cat "${script_path}/script" | sed "s/LSS-HOSTNAME-REPLACE/${hostname_inventory}/g" 2>&1
 
 	# SHOW REGULAR SCRIPT
