Update lss-srv

diff --git a/lss-srv b/lss-srv
--- a/lss-srv
+++ b/lss-srv
@@ -226,7 +226,7 @@ function action_list() {
 function action_get() {
 	# SHOW HOSTNAME SCRIPT -> replace in script code LSS-HOSTNAME-REPLACE for MAC
 	if [ -e "${script_path/hostname}" ]; then
-		get_hostname_inventory "$mac" || { log "$m" "$hostname" "get-hostname_error" "$script" "Error get-hostname for mac: $m"; exit 1; }
+		get_hostname_inventory "$mac" || { log "$m" "$hostname" "get-hostname_error" "$script_path" "Error get-hostname for mac: $m"; exit 1; }
 		cat "${script_path}/script" | sed "s/LSS-HOSTNAME-REPLACE/${hostname_inventory}/g" 2>&1
 
 	# SHOW REGULAR SCRIPT
