Update lss-srv

diff --git a/lss-srv b/lss-srv
--- a/lss-srv
+++ b/lss-srv
@@ -198,7 +198,7 @@ function get_hostname_inventory() {
 function action_list() {
 	# GET INVENTORY HOSTNAME (exit on error)
 	if [ "$check_hostnames" ]; then
-		get_hostname_inventory "$mac" || { log "$m" "$hostname" "list_error" "" "Error inventory get-hostname for mac: $m"; exit 1; }
+		get_hostname_inventory "$mac" || { log "$mac" "$hostname" "LIST_ERROR" "" "Error inventory get-hostname for mac: $m"; exit 1; }
 	fi
 
 	# LIST PENDING SCRIPTS
@@ -233,6 +233,9 @@ function action_list() {
 
 	# Print selected scripts list
 	echo "$list"
+
+	# Log list
+	log "$mac" "$hostname" "LIST" "|${list//$'\n'/|}|"
 }
 
 
